export const events = [
  {
    title: "Fall Kickoff - Intro to Design",
    link: "https://www.instagram.com/p/CF3HxwKnQWH/?igshid=YmMyMTA2M2Y=",
    image: "20201008",
    date: 20201008,
    time: 1700,
    location: "Zoom",
    slidelink: "https://docs.google.com/presentation/d/1YyOCvDqtAAnsRqBm8kM7UXTvJ5HRc0Y4/edit?usp=sharing&ouid=113563460131626668374&rtpof=true&sd=true/",
    videolink: "https://drive.google.com/file/d/17z1XLRi-Oxl72Yqf6V_-VZDLSAS4OwD6/view?usp=sharing/",
  },
  {
    title: "Game Night Social",
    link: "https://www.instagram.com/p/CGJFv1VnGz8/?igshid=YmMyMTA2M2Y=",
    image: "20201015",
    date: 20201015,
    time: 1700,
    location: "Zoom",
  },
  {
    title: "Intern Panel",
    link: "https://www.instagram.com/p/CGi88jknfAo/?igshid=YmMyMTA2M2Y=",
    image: "20201022",
    date: 20201022,
    time: 1700,
    location: "Zoom",
    slidelink: "https://docs.google.com/presentation/d/1Hl_f0UIn9DDNpixheLGnu-DFag4_KD5m/edit?usp=sharing&ouid=113563460131626668374&rtpof=true&sd=true",
    videolink: "https://drive.google.com/file/d/1s3VDtUe3VYuI7xZuQ-popRkcEhJudqzB/view?usp=sharing",
  },
  {
    title: "Scary Movie Social",
    link: "https://www.instagram.com/p/CG0-ju0BxiS/?igshid=YmMyMTA2M2Y=",
    image: "20201029",
    date: 20201029,
    time: 1700,
    location: "Zoom",
  },
  {
    title: "Resume Workshop",
    link: "https://www.instagram.com/p/CHHADPgBFQu/?igshid=YmMyMTA2M2Y=",
    image: "20201105",
    date: 20201105,
    time: 1700,
    location: "Zoom",
    slidelink: "https://docs.google.com/presentation/d/1icEjb40SxUrqYkFmcODwU-mpGm-SVo-1/edit?usp=sharing&ouid=113563460131626668374&rtpof=true&sd=true",
  },
  {
    title: "Speed Friending Social + Design Buds Reveal",
    link: "https://www.instagram.com/p/CHT2TM4BrO0/?igshid=YmMyMTA2M2Y=",
    image: "20201112",
    date: 20201112,
    time: 1700,
    location: "Zoom",
    slidelink: "https://docs.google.com/presentation/d/1rRW1nAfEcJoKXsJAQALIERBvmBQVdymT/edit?usp=sharing&ouid=113563460131626668374&rtpof=true&sd=true",
  },
  {
    title: "Camp DCo Pt. 1 – User Research",
    link: "https://www.instagram.com/p/CHbrsSsg8-e/?igshid=YmMyMTA2M2Y=",
    image: "20201117",
    date: 20201117,
    time: 1700,
    location: "Zoom",
    slidelink: "https://docs.google.com/presentation/d/1XW15x5QTe7NwMYt-0zMwgy91J5Z5ADNp/edit?usp=sharing&ouid=113563460131626668374&rtpof=true&sd=true",
    videolink: "https://drive.google.com/file/d/1xNjVLgrCXMbdooKHJeJYMl26Uk1lS8iD/view?usp=sharing",
  },
  {
    title: "Camp DCo Pt. 2 – Wireframing + Visual/Brand Design",
    link: "https://www.instagram.com/p/CHbrsSsg8-e/?igshid=YmMyMTA2M2Y=",
    image: "20201119",
    date: 20201119,
    time: 1700,
    location: "Zoom",
    slidelink: "https://docs.google.com/presentation/d/1e1S_8mzfIZtGSkoadgdtFOsWwgJcuQns/edit?usp=sharing&ouid=113563460131626668374&rtpof=true&sd=true",
    videolink: "https://drive.google.com/file/d/1eKUKydkrGcO8xRSYv12QyAeP0uTZgjJj/view?usp=sharing",
  },
  {
    title: "Unwrapping the Online Interview Process",
    link: "https://www.instagram.com/p/CIPGU9AM-Iu/?igshid=YmMyMTA2M2Y=",
    image: "20201203",
    date: 20201203,
    time: 1700,
    location: "Zoom",
    slidelink: "https://docs.google.com/presentation/d/1kuXDZMp9fp-Fu-I2rCW63Q8vIvzipioY/edit?usp=sharing&ouid=113563460131626668374&rtpof=true&sd=true",
    videolink: "https://drive.google.com/file/d/1Em13qCzPBGKahRZcdkj2v9jK3sJvpNIg/view?usp=sharing",
  },
  {
    title: "End of Quarter Celebration",
    link: "https://www.instagram.com/p/CIhZ856DBFl/?igshid=YmMyMTA2M2Y=",
    image: "20201210",
    date: 20201210,
    time: 1700,
    location: "Zoom",
  },
  {
    title: "Crafting Your Taste",
    link: "https://www.instagram.com/p/CJpOJGqM22l/?igshid=YmMyMTA2M2Y=",
    image: "20210114",
    date: 20210114,
    time: 1700,
    location: "Zoom",
    slidelink: "https://docs.google.com/presentation/d/161TwmRoCU9FWLTYBjqobwZTNonmfbjA2/edit?usp=sharing&ouid=113563460131626668374&rtpof=true&sd=true",
    videolink: "https://drive.google.com/file/d/1ASyu3URq009Gvdq12RdXYeWhj_6mKn47/view?usp=sharing",

  },
  {
    title: "Cross-Cultural Design",
    link: "https://www.instagram.com/p/CKP2Ah5Do7T/?igshid=YmMyMTA2M2Y=",
    image: "20210121",
    date: 20210121,
    time: 1700,
    location: "Zoom",
    slidelink: "https://docs.google.com/presentation/d/1WQ3fZFnZE7EkeopCKtyWCopj0tujDUOs/edit?usp=sharing&ouid=113563460131626668374&rtpof=true&sd=true",
    videolink: "https://drive.google.com/file/d/1FKBAxpNbfDyTrJ0LMVNysDQ4tkDBuykZ/view?usp=sharing",
  },
  {
    title: "Spark AR Workshop",
    link: "https://www.instagram.com/p/CKX45ZZjZP9/?igshid=YmMyMTA2M2Y=",
    image: "20210128",
    date: 20210128,
    time: 1700,
    location: "Zoom",
    slidelink: "https://docs.google.com/presentation/d/1ELVzMmDOyggNE_rH6biONe76PWNCbaZt/edit?usp=sharing&ouid=113563460131626668374&rtpof=true&sd=true",
    videolink: "https://drive.google.com/file/d/1atMC9ssl18q7gGAwJimI6bDcxCkU-vdU/view?usp=sharing",
  },
  {
    title: "Bob Ross Night",
    link: "https://www.instagram.com/p/CKxUZXiDWsm/?igshid=YmMyMTA2M2Y=",
    image: "20210204",
    date: 20210204,
    time: 1700,
    location: "Zoom",
  },
  {
    title: "Designing for Social Impact",
    link: "https://www.instagram.com/p/CK0CIALDIV8/?igshid=YmMyMTA2M2Y=",
    image: "20210211",
    date: 20210211,
    time: 1700,
    location: "Zoom",
    slidelink: "https://docs.google.com/presentation/d/1ux1g_kU8XMR-8WP5y8HOAKdskGyyu9MJ/edit?usp=sharing&ouid=113563460131626668374&rtpof=true&sd=true",
  },
  {
    title: "Designer to Developer Handoff",
    link: "https://www.instagram.com/p/CLYGp5kDn3O/?igshid=YmMyMTA2M2Y=",
    image: "20210218",
    date: 20210218,
    time: 1700,
    location: "Zoom",
    slidelink: "https://docs.google.com/presentation/d/1PLvgJrkAiKLQ5_UQdtXhNK_mlGipzDEv/edit?usp=sharing&ouid=113563460131626668374&rtpof=true&sd=true",
    videolink: "https://drive.google.com/file/d/1tiVFFE4HlpJLUIDn_VJlr0r9a8fdJqJV/view?usp=sharing",
  },
  {
    title: "How to Win Your First Designathon",
    link: "https://www.instagram.com/p/CLnaVYcD3VI/?igshid=YmMyMTA2M2Y=",
    image: "20210225",
    date: 20210225,
    time: 1700,
    location: "Zoom",
    slidelink: "https://docs.google.com/presentation/d/1rUW9dXyX4Ba-FAbLCQJdnhmRH_ifH6mN/edit?usp=sharing&ouid=113563460131626668374&rtpof=true&sd=true",
    videolink: "https://drive.google.com/file/d/1RrWXweb19Gm8c2Wo6UkCZoSAAkGWxJWu/view?usp=sharing",
  },
  {
    title: "End of Quarter Celebration",
    link: "https://www.instagram.com/p/CMLtYKhsquG/?igshid=YmMyMTA2M2Y=",
    image: "20210311",
    date: 20210311,
    time: 1700,
    location: "Zoom",
  },
  {
    title: "Design Co: Live on Discord",
    link: "https://www.instagram.com/p/CNYeYTUhX8F/?igshid=YmMyMTA2M2Y=",
    image: "20210408",
    date: 20210408,
    time: 1700,
    location: "Zoom",
  },
  {
    title: "Fireside Chat with Fjord: Design and Innovation",
    link: "https://www.instagram.com/p/CNoM8CFD9Gc/?igshid=YmMyMTA2M2Y=",
    image: "20210415",
    date: 20210415,
    time: 1600,
    location: "Zoom",
    slidelink: "https://www.facebook.com/events/507309310433424/",
    videolink: "https://drive.google.com/file/d/1Oec_2fxbAXfJ4O3WMmFe9LBd1pXpo65t/view?usp=sharing",
  },
  {
    title: "Figma: Beyond the Basics",
    link: "https://www.instagram.com/p/CN_dRZRjqYd/?igshid=YmMyMTA2M2Y=",
    image: "20210429",
    date: 20210429,
    time: 1700,
    location: "Zoom",
    slidelink: "https://docs.google.com/presentation/d/1SUix7cElebVRA1Rpw7eMObb2FZf_PWtA/edit?usp=sharing&ouid=113563460131626668374&rtpof=true&sd=true",
    videolink: "https://drive.google.com/file/d/1ulKnr15PfOz6t2zMtGz47KCC2vW0GPyF/view?usp=sharing",
  },
  {
    title: "Portfolio Prep Talk",
    link: "https://www.instagram.com/p/CORXR7UNDtU/?igshid=YmMyMTA2M2Y=",
    image: "20210506",
    date: 20210506,
    time: 1700,
    location: "Zoom",
    slidelink: "https://docs.google.com/presentation/d/10cuK0qFyVKSDE2IA9TnHhLypZsjoucTYwBP2QGS4_xY/edit?usp=sharing",
  },
  {
    title: "It's a Small (Design) World",
    link: "https://www.instagram.com/p/CObunabthcx/?igshid=YmMyMTA2M2Y=",
    image: "20210513",
    date: 20210513,
    time: 1700,
    location: "Zoom",
    slidelink: "https://docs.google.com/presentation/d/1UALCgD8dmCjEKjHwiLFUFFJoF_V66-4fsh4YsMSDSLI/edit?usp=sharing",
  },
  {
    title: "We’re Not Really Strangers, We’re Designers",
    link: "https://www.instagram.com/p/CPe-bYhDeoE/?igshid=YmMyMTA2M2Y=",
    image: "20210603",
    date: 20210603,
    time: 1700,
    location: "Zoom",
  },
  {
    title: "DEI in Industry with Service Now",
    link: "https://www.facebook.com/events/204020048419044/",
    image: "20210825",
    date: 20210825,
    time: 1700,
    location: "Zoom",
  },
  {
    title: "Fall Kickoff - Intro to Design",
    link: "https://www.instagram.com/p/CUYpNgxM3so/?igshid=YmMyMTA2M2Y=",
    image: "20211006",
    date: 20211006,
    time: 1830,
    location: "Zoom",
    slidelink: "https://docs.google.com/presentation/d/1gaaLyT-MwEW8Tr2FNSznhuANNrmDDL8dFmxI4b7d3V0/edit?usp=sharing",
    videolink: "https://drive.google.com/file/d/1pngsMMZctWr6aEWYlWZGuGH6Ue-o9FPF/view?usp=sharing",
  },
  {
    title: "Camp DCo: “Intro to _” Series",
    link: "https://www.instagram.com/p/CU6aRoGF_gk/?igshid=YmMyMTA2M2Y=",
    image: "20211016",
    date: 20211016,
    time: 1000,
    location: "Zoom",
    slidelink: "https://drive.google.com/drive/folders/1b59lylQmJiQbjOywFzRxvk8oTQsVQtFH?usp=sharing",
    videolink: "https://drive.google.com/drive/folders/1mhsQshQYEaON96IroYsuA4sELPIP8ACp?usp=sharing",
  },
  {
    title: "Intern Panel",
    link: "https://www.instagram.com/p/CVB0Qe1N56h/?igshid=YmMyMTA2M2Y=",
    image: "20211020",
    date: 20211020,
    time: 1830,
    location: "Zoom",
    slidelink: "https://docs.google.com/presentation/d/1mBgvsqn5i7QqrlYtTvxwJUqKvp_id8KVZbAnQu-m8Ac/edit?usp=sharing",
    videolink: "https://drive.google.com/file/d/1wveBXBXcGBZY-NNnkxJmVqjz_tcJb43V/view?usp=sharing",
  },
  {
    title: "Ice Skating Social",
    link: "https://www.instagram.com/p/CVeVjwssfud/?igshid=YmMyMTA2M2Y= ",
    image: "20211029",
    date: 20211029,
    time: 1900,
    location: "UTC ICE",
  },
  {
    title: "Resume Workshop",
    link: "https://www.instagram.com/p/CVmDHL5LaDE/?igshid=YmMyMTA2M2Y=",
    image: "20211103",
    date: 20211103,
    time: 1830,
    location: "Zoom",
    slidelink: "https://docs.google.com/presentation/d/1kTbX4BArfRwePcJ6C5QMGK4wVyea8wxYpxYLr2VnbuM/edit?usp=sharing",
    videolink: "https://drive.google.com/file/d/1xuduab6lTEODz78v1MMkYr6dxNaKqWJr/view?usp=sharing",
  },
  {
    title: "Portfolio Workshop",
    link: "https://www.instagram.com/p/CV36FUABgzr/?igshid=YmMyMTA2M2Y=",
    image: "20211110",
    date: 20211110,
    time: 1830,
    location: "Dolores Huerta Room",
    slidelink: "https://docs.google.com/presentation/d/1onu3iNK24KfLojJpDi3AgowYTsi7P77Sn4EWWkybJqk/edit?usp=sharing",
  },
  {
    title: "Interviewing Workshop",
    link: "https://www.instagram.com/p/CWMHUj0AHz9/?igshid=YmMyMTA2M2Y=",
    image: "20211117",
    date: 20211117,
    time: 1830,
    location: "Zoom",
    slidelink: "https://docs.google.com/presentation/d/1S4uOpyGHp3WMoHiWR294MRgyisRqtP5oNMaHkDCee2Y/edit?usp=sharing",
    videolink: "https://drive.google.com/file/d/1mxoyEWXCvECdN9pCpdBzPILTENUgetWA/view?usp=sharing",
  },
  {
    title: "End of Quarter Celebration",
    link: "https://www.instagram.com/p/CWrpKbZtU9j/?igshid=YmMyMTA2M2Y=",
    image: "20211201",
    date: 20211201,
    time: 1830,
    location: "Dolores Huerta Room",
  },
  {
    title: "A Student Survival Guide to HCI Research",
    link: "https://www.instagram.com/p/CYaUzV3hR9A/?igshid=YmMyMTA2M2Y=",
    image: "20220113",
    date: 20220113,
    time: 1830,
    location: "Zoom",
    slidelink: "https://docs.google.com/presentation/d/1c8O5DZJv2BZ94cxyO2Q5rXK2GO91qiTvD8bJDwLNoak/edit?usp=sharing",
    videolink: "https://drive.google.com/file/d/19vpv24sJ_2R-Mg5Vjf7C9vknWB-KR3hM/view?usp=sharing",
  },
  {
    title: "World Wide Web(flow) Portfolio Workshop",
    link: "https://www.instagram.com/p/CYu7EHYp0f_/?igshid=YmMyMTA2M2Y=",
    image: "20220120",
    date: 20220120,
    time: 1830,
    location: "Zoom",
    slidelink: "https://docs.google.com/presentation/d/1vBbgymYkZZChNS63aVAE94zfLY8ZNkL_xY301cJnkzs/edit?usp=sharing",
    videolink: "https://drive.google.com/file/d/1sS_QbQv3EMxaoSY2SEam2yDSdt_a04ik/view?usp=sharing",
  },
  {
    title: "A Crash Course in After Effects Animation",
    link: "https://www.instagram.com/p/CZBDAXgrDV0/?igshid=YmMyMTA2M2Y=",
    image: "20220127",
    date: 20220127,
    time: 1830,
    location: "Zoom",
    slidelink: "https://docs.google.com/presentation/d/1H3G6pZguHxExMhYGq1We2Vu5JRKHH88ct4NU4tzHOKk/edit?usp=sharing",
    videolink: "https://drive.google.com/file/d/1h6Pt8VRaucbwGJBFcBwM_7vGKS1VmiEt/view?usp=sharing",
  },
  {
    title: "UCSD x UCD Designer Speed Dating Social",
    link: "https://www.instagram.com/p/CZQZa75paC-/?igshid=YmMyMTA2M2Y=",
    image: "20220202",
    date: 20220202,
    time: 1800,
    location: "Zoom",
  },
  {
    title: "Figma: Beyond the Classroom",
    link: "https://www.instagram.com/p/CZnQBtvrkS8/?igshid=YmMyMTA2M2Y=",
    image: "20220210",
    date: 20220210,
    time: 1830,
    location: "Zoom",
    slidelink: "https://docs.google.com/presentation/d/1RzKvTrwqGaFWw96yK2eqPYnLhymAfUmGqY82F_2lHMQ/edit?usp=sharing",
    videolink: "https://drive.google.com/file/d/1vDTXmKR7RAXX-TbjZWl0PT4yvQmXHbUQ/view?usp=sharing",
  },
  {
    title: "Reppin' Your Voice: A Personal Branding Workshop",
    link: "https://www.instagram.com/p/CZ3IL2qhXNM/?igshid=YmMyMTA2M2Y=",
    image: "20220217",
    date: 20220217,
    time: 1830,
    location: "Warren College Room in Price Center",
    slidelink: "https://docs.google.com/presentation/d/14CsfSF0S7KdLzASjvHbfuR9ruHg7A-4zu5YRiz7muG4/edit?usp=sharing",
  },
  {
    title: "Minor Dilemma, Major Decisions",
    link: "https://www.instagram.com/p/CaGeOGXIvPh/?igshid=YmMyMTA2M2Y=",
    image: "20220224",
    date: 20220224,
    time: 1830,
    location: "Zoom",
    slidelink: "https://docs.google.com/presentation/d/1oIpK-KVM2yi99IBJCHxNn2CQ03od-THXCN5jvdwDhic/edit?usp=sharing",
    videolink: "https://drive.google.com/file/d/1am25kASZOAbrypi2atSb9TLPxQsWT4DS/view?usp=sharing",
  },
  {
    title: "Glowing Up Your Class Projects",
    link: "https://www.instagram.com/p/Cak1SzUhAUL/?igshid=YmMyMTA2M2Y=",
    image: "20220303",
    date: 20220303,
    time: 1830,
    location: "Zoom",
    slidelink: "https://docs.google.com/presentation/d/1BnQ3YPOD438xQm-WZmpyB-_zgJ-LzahNsUVM7JicuaQ/edit?usp=sharing",
    videolink: "https://drive.google.com/file/d/1_f1nzGPPhMp5YwsTCAjKNPwlJymbZeYL/view?usp=sharing",
  },
  {
    title: "Study Jam with Design Co",
    link: "https://www.instagram.com/p/Cav1IX6M-ka/?igshid=YmMyMTA2M2Y= ",
    image: "20220310",
    date: 20220310,
    time: 1830,
    location: "Price Center Loop",
  },
  {
    title: "Board Q&A",
    link: "https://www.instagram.com/p/CbsxXNIBEPN/?igshid=YmMyMTA2M2Y==",
    image: "20220330",
    date: 20220330,
    time: 1830,
    location: "Discord",
  },
  {
    title: "Extending Your Design Career",
    link: "https://www.instagram.com/p/Cb8zyynBAJN/?igshid=YmMyMTA2M2Y=",
    image: "20220406",
    date: 20220406,
    time: 1830,
    location: "Zoom",
    slidelink: "https://docs.google.com/presentation/d/1m24Smkreld-IwkFH9T6B2LrwYk49eDdiqNlqkX6PsvY/edit?usp=sharing",
    videolink: "https://drive.google.com/file/d/1zks1XSK95lpyEMiq5T1NaagMsQccWAtq/view?usp=sharing",
  },
  {
    title: "Wushiland Boba Run",
    link: "https://www.instagram.com/p/CcHaGZKDpdR/?igshid=YmMyMTA2M2Y=",
    image: "20220413",
    date: 20220413,
    time: 1730,
    location: "Wushiland Boba Utc",
  },
  {
    title: "Pushin' P(ortfolio Interviews)",
    link: "https://www.instagram.com/p/CcUNtVSrl9a/?igshid=YmMyMTA2M2Y=",
    image: "20220420",
    date: 20220420,
    time: 1730,
    location: "Warren College Room",
    slidelink: "https://docs.google.com/presentation/d/1lnIhGQrMUPthIc1UgN4auuvNdJMZmfH6atPgg8YWWZg/edit?usp=sharing",
  },
  {
    title: "Accessibility and Inclusivity in Design",
    link: "https://www.instagram.com/p/CcolT_aBqYn/?igshid=YmMyMTA2M2Y=",
    image: "20220427",
    date: 20220427,
    time: 1830,
    location: "Warren College Room",
    slidelink: "https://docs.google.com/presentation/d/1iual_twaXr6-bLbvYrVIU7AF6LKvZiAMXiFkM8iVz80/edit?usp=sharing",
  },
  {
    title: "Alumni Panel",
    link: "https://www.instagram.com/p/Cc61BipI8Uu/?igshid=YmMyMTA2M2Y=",
    image: "20220505",
    date: 20220505,
    time: 1830,
    location: "Design & Innovation Building: The Basement",
    slidelink: "https://docs.google.com/presentation/d/1nKGkuVOx-YbAoraWDoHere09BK--DmjnEgqE1nkt4GI/edit?usp=sharing",
  },
  {
    title: "Design Co x Design at UCI: Cross-Functional Design",
    link: "https://www.instagram.com/p/CdmDzlBBshp/?igshid=YmMyMTA2M2Y=",
    image: "20220518",
    date: 20220518,
    time: 2000,
    location: "Zoom",
    slidelink: "https://docs.google.com/presentation/d/1OKhZjs0EIPzpPAAoWsUC_MqNNFKfLZ4WyxZHo-IFMHo/edit?usp=sharing"
  },
  {
    title: "Design Co x WIC: Designer <> Developer Handoff",
    link: "https://www.instagram.com/p/CduUiXuhvvK/?igshid=YmMyMTA2M2Y=",
    image: "20220525",
    date: 20220525,
    time: 1830,
    location: "CSE Building Basement",
    slidelink: "https://docs.google.com/presentation/d/1jF7S5XlbRgQg8PwNS39G4E4v4IEy1zplbJbcFywacRs/edit?usp=sharing"
  },
  {
    title: "Yogurt World Social",
    link: "https://www.instagram.com/p/CeNPhELLTt9/?igshid=YmMyMTA2M2Y=",
    image: "20220601",
    date: 20220601,
    time: 1830,
    location: "Yogurt World",
  },
  {
    title: "Build Up: DEI Speaker Series",
    link: "https://www.instagram.com/p/Cgzn5zTts9F/?igshid=YmMyMTA2M2Y=",
    image: "20220804",
    date: 20220804,
    time: 1600,
    location: "Zoom",
  },
  {
    title: "Design Co: Fall Kickoff",
    link: "https://www.instagram.com/p/Ci9D1cSOLyz/?utm_source=ig_web_button_share_sheet",
    image: "20220928",
    date: 20220928,
    time: 1830,
    location: "Design & Innovation Building 202",
    slidelink: "https://docs.google.com/presentation/d/1LGiWS70HZk82z1HRrOHVE4QfQ9MwX2Df4NULWm5Nwzg/edit?usp=sharing"
  },
  {
    title: "Branches of UX",
    link: "https://www.instagram.com/p/CjJ72FCsL5Z/?igshid=YmMyMTA2M2Y=",
    image: "20221005",
    date: 20221005,
    time: 1830,
    location: "Design & Innovation Building 202",
    slidelink: "https://docs.google.com/presentation/d/1_DbEYgN_LIToWagwtFJHG18dhHqv2jkfqWlKEPyB0ko/edit?usp=sharing"
  },
  {
    title: "Camp DCo",
    link: "https://www.instagram.com/p/CjUIIeVvXyK/?igshid=YmMyMTA2M2Y=",
    image: "20221010",
    date: 20221010,
    time: 1830,
    location: "Design & Innovation Building 121",
    slidelink: "https://drive.google.com/drive/folders/1Xl9-A3mCHAx6GiRN0A7YsaSzPV6413ok?usp=sharing",
    description: "Calling all aspiring designers, developers, and researchers! Take the first plunge into various topics in design at Camp DCo, our annual introduction series for beginners."
  },
  {
    title: "Design Lab x Design Co Mixer",
    link: "https://www.instagram.com/p/CjRqM6Ovvgj/?igshid=YmMyMTA2M2Y=",
    image: "20221013",
    date: 20221013,
    time: 1100,
    location: "Design & Innovation Building 3rd Floor",
    description: "Meet DLab faculty, interns, alumni, and company representatives at the 3rd floor of the Design and Innovation Building. We’ll have speed networking activities, speakers from the Design Lab and Design Co, gift bag giveaways, company info booths, and more! Complimentary food and refreshments will be provided."
  },
  {
    title: "Intern Panel",
    link: "https://www.instagram.com/p/CjrTgglSRQv",
    image: "20221019",
    date: 20221019,
    time: 1830,
    location: "Design & Innovation Building 202",
    slidelink: "https://docs.google.com/presentation/d/14BEv5Y7s27nHCI0eF9tLgJwQd-vtM675F3BKYj0lXsY/edit?usp=sharing",
    description: "Interns today, industry professionals tomorrow. Get ready for our annual Intern Panel, where you’ll meet product design, UX research, and graphic design interns from companies like Meta, HP, Evil Geniuses, and more!"
  },
  {
    title: "Revamp Your Resume with Deloitte",
    link: "https://www.instagram.com/p/CkTv5T0hwkX/?igshid=YmMyMTA2M2Y=",
    image: "20221102",
    date: 20221102,
    time: 1830,
    location: "Design & Innovation Building 202",
    description: "The spooky season can be full of jump scares, but don’t let job applications be one of them! To prepare for our annual design career fair, Stride, Design Co is hosting a resume workshop with Deloitte to share the best practices for designing your resume and impressing recruiters."
  },
  {
    title: "Portfolio Day",
    link: "https://www.instagram.com/p/CkZwc4QBYV4",
    image: "20221105",
    date: 20221105,
    time: 1300,
    location: "Design & Innovation Building 202",
    description: "Prepping for Stride? Applying for internships? Need one last push to finally tackle your portfolio? Join Design Co at our upcoming Portfolio Day to build out and get feedback on your portfolio—all experience levels welcome!"
  },
  {
    title: "Stride",
    link: "https://www.instagram.com/p/Cke-ZDvLqqQ/",
    image: "20221108",
    date: 20221108,
    time: 1000,
    location: "Zoom",
    description: "Gear up for Stride, our annual design-centric career fair! Stride aims to connect aspiring designers with company representatives by providing a space for meaningful conversation and engagement."
  },
];

// if npm start fails you npm rebuild node-sass
