export const team = [
  {
    id: "julia-n",
    name: "Julia Nguyen",
    role: "Creative Director",
    link: "https://julianguyen.co/",
    gradYear: 2021,
  },
  {
    id: "nhu",
    name: "Nhu Luong",
    role: "Creative Director",
    link: "http://nhu777.net",
    gradYear: 2021,
  },
  {
    id: "jamin",
    name: "Jamin Capulong",
    role: "Community Engagement Coordinator",
    link: "https://www.linkedin.com/in/jamin-nick-capulong/",
    gradYear: 2020,
  },
  {
    id: "alison",
    name: "Alison Chen",
    role: "Industry Relations Director",
    link: "https://www.linkedin.com/in/ealisonchen/",
    gradYear: 2021,
  },
  {
    id: "amy",
    name: "Amy An",
    role: "Industry Relations Coordinator",
    link: "http://amyan.me/",
    gradYear: 2021,
  },
  {
    id: "dana",
    name: "Dana Chou",
    role: "Photographer/Videographer",
    link: "https://www.danachou.net/",
    gradYear: 2021,
  },
  {
    id: "daniel",
    name: "Daniel Li",
    role: "Content Strategist/Writer",
    link: "http://linkedin.com/in/lidaniel99",
    gradYear: 2021,
  },
  {
    id: "julia-c",
    name: "Julia Chu",
    role: "Community Engagement Coordinator",
    link: "https://www.juliachudesign.com/",
    gradYear: 2021,
  },
  {
    id: "nicolette",
    name: "Nicolette Shin",
    role: "Social Media Coordinator",
    link: "http://linkedin.com/in/nicoletteshin526/",
    gradYear: 2021,
  },
  {
    id: "paridhi",
    name: "Paridhi Khaitan",
    role: "Web Developer",
    link: "https://www.paridhikhaitan.me/",
    gradYear: 2021,
  },
  {
    id: "quinn",
    name: "Quinn Vu",
    role: "Marketing Director",
    link: "https://quinn-vu.com/work",
    gradYear: 2021,
  },
  {
    id: "stella",
    name: "Stella Seki",
    role: "Community Engagement Director",
    link: "https://www.stellaseki.com/",
    gradYear: 2021,
  },
  {
    id: "winson",
    name: "Winson Dieu",
    role: "Industry Relations Director",
    link: "https://winsondieu.com",
    gradYear: 2021,
  },
  {
    id: "braeanne",
    name: "Braeanne Oribello",
    role: "Visual + Brand Designer",
    link: "http://braeanneori.com/",
    gradYear: 2022,
  },
  {
    id: "mylinh",
    name: "Mylinh Lac",
    role: "Community Engagement Coordinator",
    link: "https://www.linkedin.com/in/mylinh-lac/",
    gradYear: 2022,
  },
  {
    id: "staci",
    name: "Staci Lin",
    role: "Industry Relations Coordinator",
    link: "http://stacilin.com/",
    gradYear: 2022,
  },
  {
    id: "adam",
    name: "Adam Syed",
    role: "Web Developer",
    link: "https://syedadam.com/",
    gradYear: 2022,
  },
  {
    id: "megan",
    name: "Megan Tan",
    role: "Visual + Brand Designer",
    link: "http://linkedin.com/in/megan-tan-31a2471a5",
    gradYear: 2023,
  },
  // {
  //   id: "steven",
  //   name: "Steven Chen",
  //   role: "Director of Industry Relations",
  //   link: "https://www.stevenychen.com/",
  //   gradYear: 2020
  // },
  // {
  //   id: "vicky",
  //   name: "Vicky Ly",
  //   role: "Director of Marketing and Operations",
  //   link: "https://vickyly.co",
  //   gradYear: 2020
  // },
  // {
  //   id: "andrew",
  //   name: "Andrew Zhen",
  //   role: "Web Developer",
  //   link: "https://ajzhen.com",
  //   gradYear: 2020
  // },
  // {
  //   id: "brittany",
  //   name: "Brittany Newton",
  //   role: "Director of Community, Growth and Strategy",
  //   link: "https://www.linkedin.com/in/brittany-newton-648452133/",
  //   gradYear: 2020
  // },
];
