export const team = [
  {
    id: "megan",
    name: "Megan Tan",
    role: "Co-Creative Director",
    link: "http://linkedin.com/in/megan-tan-31a2471a5",
    gradYear: 2023,
    gif: "https://res.cloudinary.com/design-co-ucsd/image/upload/v1663837980/designco/about/team-gifs/megan_cpulwb.gif",
    img: "https://res.cloudinary.com/design-co-ucsd/image/upload/v1665182835/designco/about/team-photos/megan_vom41e.png",
  },
  {
    id: "maria",
    name: "Maria Dhilla",
    role: "Industry Relations Director",
    link: "https://mariadhilla.myportfolio.com/",
    gradYear: 2023,
    gif: "https://res.cloudinary.com/design-co-ucsd/image/upload/v1663837979/designco/about/team-gifs/maria_ew1spu.gif",
    img: "https://res.cloudinary.com/design-co-ucsd/image/upload/v1665182906/designco/about/team-photos/maria_kgqecb.png",
  },
  {
    id: "juna",
    name: "Juna Kim",
    role: "Co-Creative Director",
    link: "https://www.junakim.design",
    gradYear: 2023,
    gif: "https://res.cloudinary.com/design-co-ucsd/image/upload/v1663837926/designco/about/team-gifs/juna_lsgx1m.gif",
    img: "https://res.cloudinary.com/design-co-ucsd/image/upload/v1665182837/designco/about/team-photos/juna_wkpohp.png",
  },
  {
    id: "tiffany",
    name: "Tiffany Zhong",
    role: "Co-Marketing Director + Media Coordinator",
    link: "https://www.linkedin.com/in/tiffany-zhong-2841a718b/",
    gradYear: 2023,
    gif: "https://res.cloudinary.com/design-co-ucsd/image/upload/v1663837948/designco/about/team-gifs/tiffany_zsbavy.gif",
    img: "https://res.cloudinary.com/design-co-ucsd/image/upload/v1665182963/designco/about/team-photos/tiffany_ymj4mq.png",
  },
  {
    id: "jodie",
    name: "Jodie Li",
    role: "Internal Director",
    link: "https://www.jodieli.site/",
    gradYear: 2023,
    gif: "https://res.cloudinary.com/design-co-ucsd/image/upload/v1663837969/designco/about/team-gifs/jodie_r35qrx.gif",
    img: "https://res.cloudinary.com/design-co-ucsd/image/upload/v1665182884/designco/about/team-photos/jodie_j3lvvh.png",
  },
  {
    id: "emilyjao",
    name: "Emily Jao",
    role: "Co-Marketing Director",
    link: "https://emilysjao.wixsite.com/my-site",
    gradYear: 2024,
    gif: "https://res.cloudinary.com/design-co-ucsd/image/upload/v1663837888/designco/about/team-gifs/emilyjao_t51mwq.gif",
    img: "https://res.cloudinary.com/design-co-ucsd/image/upload/v1665182963/designco/about/team-photos/emilyjao_tyq2je.png",
  },
  {
    id: "emilyyu",
    name: "Emily Yu",
    role: "Director of Community",
    link: "https://www.linkedin.com/in/emily-yu-365943225/",
    gradYear: 2025,
    gif: "https://res.cloudinary.com/design-co-ucsd/image/upload/v1663837892/designco/about/team-gifs/emilyyu_zp81xq.gif",
    img: "https://res.cloudinary.com/design-co-ucsd/image/upload/v1665182776/designco/about/team-photos/emilyyu_roxviz.png",
  },
  {
    id: "leann",
    name: "Leann Gamboa",
    role: "Visual + Web Developer",
    link: "https://www.linkedin.com/in/leanngamboa/",
    gradYear: 2022,
    gif: "https://res.cloudinary.com/design-co-ucsd/image/upload/v1663837972/designco/about/team-gifs/leann_ijibfs.gif",
    img: "https://res.cloudinary.com/design-co-ucsd/image/upload/v1665182835/designco/about/team-photos/leann_y4oc0e.png",
  },
  /* {
    id: "tracy",
    name: "Tracy Nguyen",
    role: "Industry Relations Coordinator",
    link: "https://www.linkedin.com/in/tracy-trang-nguyen/",
    gradYear: 2023,
    gif: "",
  
  img: "",}, */
  {
    id: "shawn",
    name: "Shawn Kim",
    role: "Web Developer",
    link: "https://www.linkedin.com/in/shawn-j-kim/",
    gradYear: 2023,
    gif: "https://res.cloudinary.com/design-co-ucsd/image/upload/v1663831878/designco/about/team-gifs/shawn_up1ai3.gif",
    img: "https://res.cloudinary.com/design-co-ucsd/image/upload/v1665182845/designco/about/team-photos/shawn_soi3ap.png",
  },
  {
    id: "rainee",
    name: "Rainee Pei",
    role: "Media Coordinator",
    link: "https://www.raineepei.com/",
    gradYear: 2023,
    gif: "https://res.cloudinary.com/design-co-ucsd/image/upload/v1663837933/designco/about/team-gifs/rainee_btufff.gif",
    img: "https://res.cloudinary.com/design-co-ucsd/image/upload/v1665182955/designco/about/team-photos/rainee_axawij.png",
  },
  {
    id: "hannah",
    name: "Hannah Yick",
    role: "Content Strategist/Writer",
    link: "https://www.linkedin.com/in/hannahyick/",
    gradYear: 2023,
    gif: "https://res.cloudinary.com/design-co-ucsd/image/upload/v1663837899/designco/about/team-gifs/hannah_a8eu18.gif",
    img: "https://res.cloudinary.com/design-co-ucsd/image/upload/v1665182962/designco/about/team-photos/hannah_qd4xba.png",
  },
  {
    id: "donna",
    name: "Donna Kim",
    role: "Operations Coordinator",
    link: "https://www.linkedin.com/in/dawnakim/",
    gradYear: 2023,
    gif: "https://res.cloudinary.com/design-co-ucsd/image/upload/v1663837953/designco/about/team-gifs/donna_rfkg32.gif",
    img: "https://res.cloudinary.com/design-co-ucsd/image/upload/v1665182885/designco/about/team-photos/donna_x8myvy.png",
  },
  {
    id: "ricky",
    name: "Ricardo Sedano",
    role: "Visual + Brand Designer",
    link: "linkedin.com/in/ricardo-sedano",
    gradYear: 2023,
    gif: "https://res.cloudinary.com/design-co-ucsd/image/upload/v1663837932/designco/about/team-gifs/ricky_ennyxu.gif",
    img: "https://res.cloudinary.com/design-co-ucsd/image/upload/v1665182844/designco/about/team-photos/ricky_p6o1js.png",
  },
  {
    id: "meshach",
    name: "Meshach Adoe",
    role: "Web Developer",
    link: "https://www.linkedin.com/in/meshachadoe",
    gradYear: 2023,
    gif: "https://res.cloudinary.com/design-co-ucsd/image/upload/v1663837984/designco/about/team-gifs/meshach_oujofy.gif",
    img: "https://res.cloudinary.com/design-co-ucsd/image/upload/v1665182834/designco/about/team-photos/meshach_czxqsg.png",
  },
  {
    id: "grace",
    name: "Grace Lin",
    role: "Community Engagement Coordinator",
    link: "https://www.linkedin.com/in/graceerya/",
    gradYear: 2023,
    gif: "https://res.cloudinary.com/design-co-ucsd/image/upload/v1663837895/designco/about/team-gifs/grace_oswykx.gif",
    img: "https://res.cloudinary.com/design-co-ucsd/image/upload/v1665182777/designco/about/team-photos/grace_u1acws.png",
  },
  {
    id: "jonathan",
    name: "Jonathan Lum",
    role: "Community Engagement Coordinator",
    link: "https://www.linkedin.com/in/jonathan-lum/",
    gradYear: 2023,
    gif: "https://res.cloudinary.com/design-co-ucsd/image/upload/v1663837918/designco/about/team-gifs/jonathan_xodsgp.gif",
    img: "https://res.cloudinary.com/design-co-ucsd/image/upload/v1665182779/designco/about/team-photos/jonathan_pzoksh.png",
  },
  {
    id: "catherine",
    name: "Catherine Oei",
    role: "Industry Relations Coordinator",
    link: "https://www.linkedin.com/in/catherine-oei/",
    gradYear: 2023,
    gif: "",
    img: "https://res.cloudinary.com/design-co-ucsd/image/upload/v1665182905/designco/about/team-photos/catherine_xiodce.png",
  },
  {
    id: "tracey",
    name: "Tracey Du",
    role: "Web Developer",
    link: "https://www.linkedin.com/in/traceydu/",
    gradYear: 2024,
    gif: "https://res.cloudinary.com/design-co-ucsd/image/upload/v1663837866/designco/about/team-gifs/tracey_jwzaar.gif",
    img: "https://res.cloudinary.com/design-co-ucsd/image/upload/v1665182853/designco/about/team-photos/tracey_tdaqmd.png",
  },
  {
    id: "kayla",
    name: "Kayla Luong",
    role: "Content Strategist/Writer",
    link: "https://www.linkedin.com/in/kayla-l-a12641199/",
    gradYear: 2024,
    gif: "https://res.cloudinary.com/design-co-ucsd/image/upload/v1663837920/designco/about/team-gifs/kayla_zf0mgd.gif",
    img: "https://res.cloudinary.com/design-co-ucsd/image/upload/v1665182959/designco/about/team-photos/kayla_seeskl.png",
  },
  {
    id: "jocelyn",
    name: "Jocelyn Horng",
    role: "Operations Coordinator",
    link: "https://www.linkedin.com/in/jocelyn-horng-2b84121b1/",
    gradYear: 2024,
    gif: "https://res.cloudinary.com/design-co-ucsd/image/upload/v1663837957/designco/about/team-gifs/jocelyn_jkigbr.gif",
    img: "https://res.cloudinary.com/design-co-ucsd/image/upload/v1665182886/designco/about/team-photos/jocelyn_etsjxs.png",
  },
  {
    id: "brian",
    name: "Brian Liu",
    role: "Media Coordinator + Web Developer",
    link: "https://brianliu1.myportfolio.com",
    gradYear: 2024,
    gif: "https://res.cloudinary.com/design-co-ucsd/image/upload/v1663837867/designco/about/team-gifs/brian_figech.gif",
    img: "https://res.cloudinary.com/design-co-ucsd/image/upload/v1665182850/designco/about/team-photos/brian_hh46rt.png",
  },
  {
    id: "sabrina",
    name: "Sabrina Mao",
    role: "Community Engagement Coordinator",
    link: "https://www.linkedin.com/in/sabrina-mao-2aba501b8/",
    gradYear: 2024,
    gif: "https://res.cloudinary.com/design-co-ucsd/image/upload/v1663837929/designco/about/team-gifs/sabrina_ibfl8t.gif",
    img: "https://res.cloudinary.com/design-co-ucsd/image/upload/v1665182779/designco/about/team-photos/sabrina_kmq1v0.png",
  },
  {
    id: "sujana",
    name: "Sujana Nagasuri",
    role: "Operations Coordinator",
    link: "https://www.linkedin.com/in/sujana-nagasuri-943493238/",
    gradYear: 2024,
    gif: "https://res.cloudinary.com/design-co-ucsd/image/upload/v1663837859/designco/about/team-gifs/sujana_liqfys.gif",
    img: "https://res.cloudinary.com/design-co-ucsd/image/upload/v1665182885/designco/about/team-photos/sujana_ebknos.png",
  },
  {
    id: "esther",
    name: "Esther Liu",
    role: "Industry Relations Coordinator",
    link: "https://www.linkedin.com/in/esther--liu",
    gradYear: 2025,
    gif: "",
    img: "https://res.cloudinary.com/design-co-ucsd/image/upload/v1665182899/designco/about/team-photos/esther_cnazjg.png",
  },
  {
    id: "frances",
    name: "Frances Sy",
    role: "Social Media Coordinator",
    link: "https://www.linkedin.com/in/frances-sy/",
    gradYear: 2025,
    gif: "https://res.cloudinary.com/design-co-ucsd/image/upload/v1663831907/designco/about/team-gifs/frances_keifip.gif",
    img: "https://res.cloudinary.com/design-co-ucsd/image/upload/v1665182962/designco/about/team-photos/frances_szutcr.png",
  },
  {
    id: "thoa",
    name: "Thoa Nguyen",
    role: "Visual + Brand Designer",
    link: "https://www.linkedin.com/in/thoa-nguyen-99a473217/",
    gradYear: 2025,
    gif: "https://res.cloudinary.com/design-co-ucsd/image/upload/v1663837874/designco/about/team-gifs/thoa_irqejb.gif",
    img: "https://res.cloudinary.com/design-co-ucsd/image/upload/v1665182850/designco/about/team-photos/thoa_guvldl.png",
  },
  {
    id: "elise",
    name: "Elise Kim",
    role: "Industry Relations Coordinator",
    link: "https://www.linkedin.com/in/elisekim999/",
    gradYear: 2025,
    gif: "https://res.cloudinary.com/design-co-ucsd/image/upload/v1663837886/designco/about/team-gifs/elise_kvjf38.gif",
    img: "https://res.cloudinary.com/design-co-ucsd/image/upload/v1665182908/designco/about/team-photos/elise_oclfeo.png",
  },
  {
    id: "mandy",
    name: "Mandy Lai",
    role: "Finance Coordinator",
    link: "https://www.linkedin.com/in/mandy-lai-4179b91a1/",
    gradYear: 2025,
    gif: "https://res.cloudinary.com/design-co-ucsd/image/upload/v1663837968/designco/about/team-gifs/mandy_bebrif.gif",
    img: "https://res.cloudinary.com/design-co-ucsd/image/upload/v1665182884/designco/about/team-photos/mandy_izsnqe.png",
  },

  
  /*{
      id: "mylinh",
      name: "Mylinh Lac",
      role: "Director of Community, Growth, and Strategy",
      link: "https://www.linkedin.com/in/mylinh-lac/",
      gradYear: 2022,
  
    },
    {
      id: "julie",
      name: "Julie Han",
      role: "Marketing Director",
      link: "https://juliehan.webflow.io",
      gradYear: 2022,
  
    },
    {
      id: "adam",
      name: "Adam Syed",
      role: "Industry Relations Coordinator",
      link: "https://syedadam.com/",
      gradYear: 2022,
  
    },
    {
      id: "megandinh",
      name: "Megan Dinh",
      role: "Content Strategist/Writer",
      link: "https://megandinh.github.io/",
      gradYear: 2022,
  
    },
    {
      id: "amber",
      name: "Amber Lu",
      role: "Community Engagement Coordinator",
      link: "https://www.linkedin.com/in/amberlu1226/",
      gradYear: 2022,
  
    },
    {
      id: "sergio",
      name: "Sergio Ramirez",
      role: "Community Engagement Coordinator",
      link: "https://www.linkedin.com/in/sramirez2292/",
      gradYear: 2022,
  
    },
    {
      id: "staci",
      name: "Staci Lin",
      role: "Industry Relations Advisor",
      link: "http://stacilin.com/",
      gradYear: 2022,
  
    },
    {
  //   id: "jamin",
  //   name: "Jamin Capulong",
  //   role: "Director of Community, Growth, and Strategy",
  //   link: "https://www.linkedin.com/in/jamin-nick-capulong/",
  //   gradYear: 2020,
  // },
  // {
  //   id: "gisca",
  //   name: "Gisca Giancana",
  //   role: "Social Media Coordinator",
  //   link: "https://www.giscagiancana.com/",
  //   gradYear: 2022,
  // },
  */
  

  // {
  //   id: "alison",
  //   name: "Alison Chen",
  //   role: "Industry Relations Director",
  //   link: "https://www.linkedin.com/in/ealisonchen/",
  //   gradYear: 2021,
  // },
  // {
  //   id: "winson",
  //   name: "Winson Dieu",
  //   role: "Industry Relations Director",
  //   link: "https://winsondieu.com",
  //   gradYear: 2021,
  // },
  // {
  //   id: "dana",
  //   name: "Dana Chou",
  //   role: "Photographer/Videographer",
  //   link: "https://www.danachou.net/",
  //   gradYear: 2021,
  // },
  // {
  //   id: "steven",
  //   name: "Steven Chen",
  //   role: "Director of Industry Relations",
  //   link: "https://www.stevenychen.com/",
  //   gradYear: 2020  // },
  // {
  //   id: "vicky",
  //   name: "Vicky Ly",
  //   role: "Director of Marketing and Operations",
  //   link: "https://vickyly.co",
  //   gradYear: 2020  // },
  // {
  //   id: "andrew",
  //   name: "Andrew Zhen",
  //   role: "Web Developer",
  //   link: "https://ajzhen.com",
  //   gradYear: 2020  // },
  // {
  //   id: "brittany",
  //   name: "Brittany Newton",
  //   role: "Director of Community, Growth and Strategy",
  //   link: "https://www.linkedin.com/in/brittany-newton-648452133/",
  //   gradYear: 2020  // },
  // {
  //   id: "julia-n",
  //   name: "Julia Nguyen",
  //   role: "Creative Director",
  //   link: "https://julianguyen.co/",
  //   gradYear: 2021,
  // },
  // {
  //   id: "nhu",
  //   name: "Nhu Luong",
  //   role: "Creative Director",
  //   link: "https://nhu777.webflow.io/",
  //   gradYear: 2021,
  // },
  // {
  //   id: "daniel",
  //   name: "Daniel Li",
  //   role: "Content Strategist/Writer",
  //   link: "http://linkedin.com/in/lidaniel99",
  //   gradYear: 2021,
  // },
  // {
  //   id: "paridhi",
  //   name: "Paridhi Khaitan",
  //   role: "Web Developer",
  //   link: "https://www.paridhikhaitan.me/",
  //   gradYear: 2021,
  // },
  // {
  //   id: "nicolette",
  //   name: "Nicolette Shin",
  //   role: "Social Media Coordinator",
  //   link: "http://linkedin.com/in/nicoletteshin526/",
  //   gradYear: 2021,
  // },
  // {
  //   id: "julia-c",
  //   name: "Julia Chu",
  //   role: "Community Engagement Coordinator",
  //   link: "https://www.juliachudesign.com/",
  //   gradYear: 2021,
  // },
];
